/* test.c generated by valac 0.28.1, the Vala compiler
 * generated from test.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_video.h>
#include <SDL2/SDL_surface.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_events.h>
#include <stdio.h>
#include <SDL2/SDL_keycode.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TYPE_HELLO_WORLD (hello_world_get_type ())
#define HELLO_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HELLO_WORLD, HelloWorld))
#define HELLO_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_HELLO_WORLD, HelloWorldClass))
#define IS_HELLO_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HELLO_WORLD))
#define IS_HELLO_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_HELLO_WORLD))
#define HELLO_WORLD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HELLO_WORLD, HelloWorldClass))

typedef struct _HelloWorld HelloWorld;
typedef struct _HelloWorldClass HelloWorldClass;
typedef struct _HelloWorldPrivate HelloWorldPrivate;
#define _SDL_DestroyWindow0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyWindow (var), NULL)))
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))
#define _hello_world_unref0(var) ((var == NULL) ? NULL : (var = (hello_world_unref (var), NULL)))
typedef struct _ParamSpecHelloWorld ParamSpecHelloWorld;

struct _HelloWorld {
	GTypeInstance parent_instance;
	volatile int ref_count;
	HelloWorldPrivate * priv;
};

struct _HelloWorldClass {
	GTypeClass parent_class;
	void (*finalize) (HelloWorld *self);
};

struct _HelloWorldPrivate {
	SDL_Window* window;
	SDL_Surface* surface;
	SDL_Surface** surfaces;
	gint surfaces_length1;
	gint _surfaces_size_;
};

struct _ParamSpecHelloWorld {
	GParamSpec parent_instance;
};


static gpointer hello_world_parent_class = NULL;

gpointer hello_world_ref (gpointer instance);
void hello_world_unref (gpointer instance);
GParamSpec* param_spec_hello_world (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_hello_world (GValue* value, gpointer v_object);
void value_take_hello_world (GValue* value, gpointer v_object);
gpointer value_get_hello_world (const GValue* value);
GType hello_world_get_type (void) G_GNUC_CONST;
#define HELLO_WORLD_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_HELLO_WORLD, HelloWorldPrivate))
enum  {
	HELLO_WORLD_DUMMY_PROPERTY
};
void hello_world_run (HelloWorld* self);
const gchar* sdl_keycode_to_string (SDL_Keycode self);
static const char* _sdl_keycode_to_string (SDL_Keycode value);
void hello_world_load_media (HelloWorld* self);
void hello_world_init (HelloWorld* self);
void hello_world_main (void);
HelloWorld* hello_world_new (void);
HelloWorld* hello_world_construct (GType object_type);
static void hello_world_finalize (HelloWorld* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static const char* _sdl_keycode_to_string (SDL_Keycode value) {
	switch (value) {
		case SDLK_UNKNOWN:
		return "SDLK_UNKNOWN";
		case SDLK_RETURN:
		return "SDLK_RETURN";
		case SDLK_ESCAPE:
		return "SDLK_ESCAPE";
		case SDLK_BACKSPACE:
		return "SDLK_BACKSPACE";
		case SDLK_TAB:
		return "SDLK_TAB";
		case SDLK_SPACE:
		return "SDLK_SPACE";
		case SDLK_EXCLAIM:
		return "SDLK_EXCLAIM";
		case SDLK_QUOTEDBL:
		return "SDLK_QUOTEDBL";
		case SDLK_HASH:
		return "SDLK_HASH";
		case SDLK_PERCENT:
		return "SDLK_PERCENT";
		case SDLK_DOLLAR:
		return "SDLK_DOLLAR";
		case SDLK_AMPERSAND:
		return "SDLK_AMPERSAND";
		case SDLK_QUOTE:
		return "SDLK_QUOTE";
		case SDLK_LEFTPAREN:
		return "SDLK_LEFTPAREN";
		case SDLK_RIGHTPAREN:
		return "SDLK_RIGHTPAREN";
		case SDLK_ASTERISK:
		return "SDLK_ASTERISK";
		case SDLK_PLUS:
		return "SDLK_PLUS";
		case SDLK_COMMA:
		return "SDLK_COMMA";
		case SDLK_MINUS:
		return "SDLK_MINUS";
		case SDLK_PERIOD:
		return "SDLK_PERIOD";
		case SDLK_SLASH:
		return "SDLK_SLASH";
		case SDLK_0:
		return "SDLK_0";
		case SDLK_1:
		return "SDLK_1";
		case SDLK_2:
		return "SDLK_2";
		case SDLK_3:
		return "SDLK_3";
		case SDLK_4:
		return "SDLK_4";
		case SDLK_5:
		return "SDLK_5";
		case SDLK_6:
		return "SDLK_6";
		case SDLK_7:
		return "SDLK_7";
		case SDLK_8:
		return "SDLK_8";
		case SDLK_9:
		return "SDLK_9";
		case SDLK_COLON:
		return "SDLK_COLON";
		case SDLK_SEMICOLON:
		return "SDLK_SEMICOLON";
		case SDLK_LESS:
		return "SDLK_LESS";
		case SDLK_EQUALS:
		return "SDLK_EQUALS";
		case SDLK_GREATER:
		return "SDLK_GREATER";
		case SDLK_QUESTION:
		return "SDLK_QUESTION";
		case SDLK_AT:
		return "SDLK_AT";
		case SDLK_LEFTBRACKET:
		return "SDLK_LEFTBRACKET";
		case SDLK_BACKSLASH:
		return "SDLK_BACKSLASH";
		case SDLK_RIGHTBRACKET:
		return "SDLK_RIGHTBRACKET";
		case SDLK_CARET:
		return "SDLK_CARET";
		case SDLK_UNDERSCORE:
		return "SDLK_UNDERSCORE";
		case SDLK_BACKQUOTE:
		return "SDLK_BACKQUOTE";
		case SDLK_a:
		return "SDLK_a";
		case SDLK_b:
		return "SDLK_b";
		case SDLK_c:
		return "SDLK_c";
		case SDLK_d:
		return "SDLK_d";
		case SDLK_e:
		return "SDLK_e";
		case SDLK_f:
		return "SDLK_f";
		case SDLK_g:
		return "SDLK_g";
		case SDLK_h:
		return "SDLK_h";
		case SDLK_i:
		return "SDLK_i";
		case SDLK_j:
		return "SDLK_j";
		case SDLK_k:
		return "SDLK_k";
		case SDLK_l:
		return "SDLK_l";
		case SDLK_m:
		return "SDLK_m";
		case SDLK_n:
		return "SDLK_n";
		case SDLK_o:
		return "SDLK_o";
		case SDLK_p:
		return "SDLK_p";
		case SDLK_q:
		return "SDLK_q";
		case SDLK_r:
		return "SDLK_r";
		case SDLK_s:
		return "SDLK_s";
		case SDLK_t:
		return "SDLK_t";
		case SDLK_u:
		return "SDLK_u";
		case SDLK_v:
		return "SDLK_v";
		case SDLK_w:
		return "SDLK_w";
		case SDLK_x:
		return "SDLK_x";
		case SDLK_y:
		return "SDLK_y";
		case SDLK_z:
		return "SDLK_z";
		case SDLK_CAPSLOCK:
		return "SDLK_CAPSLOCK";
		case SDLK_F1:
		return "SDLK_F1";
		case SDLK_F2:
		return "SDLK_F2";
		case SDLK_F3:
		return "SDLK_F3";
		case SDLK_F4:
		return "SDLK_F4";
		case SDLK_F5:
		return "SDLK_F5";
		case SDLK_F6:
		return "SDLK_F6";
		case SDLK_F7:
		return "SDLK_F7";
		case SDLK_F8:
		return "SDLK_F8";
		case SDLK_F9:
		return "SDLK_F9";
		case SDLK_F10:
		return "SDLK_F10";
		case SDLK_F11:
		return "SDLK_F11";
		case SDLK_F12:
		return "SDLK_F12";
		case SDLK_PRINTSCREEN:
		return "SDLK_PRINTSCREEN";
		case SDLK_SCROLLLOCK:
		return "SDLK_SCROLLLOCK";
		case SDLK_PAUSE:
		return "SDLK_PAUSE";
		case SDLK_INSERT:
		return "SDLK_INSERT";
		case SDLK_HOME:
		return "SDLK_HOME";
		case SDLK_PAGEUP:
		return "SDLK_PAGEUP";
		case SDLK_DELETE:
		return "SDLK_DELETE";
		case SDLK_END:
		return "SDLK_END";
		case SDLK_PAGEDOWN:
		return "SDLK_PAGEDOWN";
		case SDLK_RIGHT:
		return "SDLK_RIGHT";
		case SDLK_LEFT:
		return "SDLK_LEFT";
		case SDLK_DOWN:
		return "SDLK_DOWN";
		case SDLK_UP:
		return "SDLK_UP";
		case SDLK_NUMLOCKCLEAR:
		return "SDLK_NUMLOCKCLEAR";
		case SDLK_KP_DIVIDE:
		return "SDLK_KP_DIVIDE";
		case SDLK_KP_MULTIPLY:
		return "SDLK_KP_MULTIPLY";
		case SDLK_KP_MINUS:
		return "SDLK_KP_MINUS";
		case SDLK_KP_PLUS:
		return "SDLK_KP_PLUS";
		case SDLK_KP_ENTER:
		return "SDLK_KP_ENTER";
		case SDLK_KP_1:
		return "SDLK_KP_1";
		case SDLK_KP_2:
		return "SDLK_KP_2";
		case SDLK_KP_3:
		return "SDLK_KP_3";
		case SDLK_KP_4:
		return "SDLK_KP_4";
		case SDLK_KP_5:
		return "SDLK_KP_5";
		case SDLK_KP_6:
		return "SDLK_KP_6";
		case SDLK_KP_7:
		return "SDLK_KP_7";
		case SDLK_KP_8:
		return "SDLK_KP_8";
		case SDLK_KP_9:
		return "SDLK_KP_9";
		case SDLK_KP_0:
		return "SDLK_KP_0";
		case SDLK_KP_PERIOD:
		return "SDLK_KP_PERIOD";
		case SDLK_APPLICATION:
		return "SDLK_APPLICATION";
		case SDLK_POWER:
		return "SDLK_POWER";
		case SDLK_KP_EQUALS:
		return "SDLK_KP_EQUALS";
		case SDLK_F13:
		return "SDLK_F13";
		case SDLK_F14:
		return "SDLK_F14";
		case SDLK_F15:
		return "SDLK_F15";
		case SDLK_F16:
		return "SDLK_F16";
		case SDLK_F17:
		return "SDLK_F17";
		case SDLK_F18:
		return "SDLK_F18";
		case SDLK_F19:
		return "SDLK_F19";
		case SDLK_F20:
		return "SDLK_F20";
		case SDLK_F21:
		return "SDLK_F21";
		case SDLK_F22:
		return "SDLK_F22";
		case SDLK_F23:
		return "SDLK_F23";
		case SDLK_F24:
		return "SDLK_F24";
		case SDLK_EXECUTE:
		return "SDLK_EXECUTE";
		case SDLK_HELP:
		return "SDLK_HELP";
		case SDLK_MENU:
		return "SDLK_MENU";
		case SDLK_SELECT:
		return "SDLK_SELECT";
		case SDLK_STOP:
		return "SDLK_STOP";
		case SDLK_AGAIN:
		return "SDLK_AGAIN";
		case SDLK_UNDO:
		return "SDLK_UNDO";
		case SDLK_CUT:
		return "SDLK_CUT";
		case SDLK_COPY:
		return "SDLK_COPY";
		case SDLK_PASTE:
		return "SDLK_PASTE";
		case SDLK_FIND:
		return "SDLK_FIND";
		case SDLK_MUTE:
		return "SDLK_MUTE";
		case SDLK_VOLUMEUP:
		return "SDLK_VOLUMEUP";
		case SDLK_VOLUMEDOWN:
		return "SDLK_VOLUMEDOWN";
		case SDLK_KP_COMMA:
		return "SDLK_KP_COMMA";
		case SDLK_KP_EQUALSAS400:
		return "SDLK_KP_EQUALSAS400";
		case SDLK_ALTERASE:
		return "SDLK_ALTERASE";
		case SDLK_SYSREQ:
		return "SDLK_SYSREQ";
		case SDLK_CANCEL:
		return "SDLK_CANCEL";
		case SDLK_CLEAR:
		return "SDLK_CLEAR";
		case SDLK_PRIOR:
		return "SDLK_PRIOR";
		case SDLK_RETURN2:
		return "SDLK_RETURN2";
		case SDLK_SEPARATOR:
		return "SDLK_SEPARATOR";
		case SDLK_OUT:
		return "SDLK_OUT";
		case SDLK_OPER:
		return "SDLK_OPER";
		case SDLK_CLEARAGAIN:
		return "SDLK_CLEARAGAIN";
		case SDLK_CRSEL:
		return "SDLK_CRSEL";
		case SDLK_EXSEL:
		return "SDLK_EXSEL";
		case SDLK_KP_00:
		return "SDLK_KP_00";
		case SDLK_KP_000:
		return "SDLK_KP_000";
		case SDLK_THOUSANDSSEPARATOR:
		return "SDLK_THOUSANDSSEPARATOR";
		case SDLK_DECIMALSEPARATOR:
		return "SDLK_DECIMALSEPARATOR";
		case SDLK_CURRENCYUNIT:
		return "SDLK_CURRENCYUNIT";
		case SDLK_CURRENCYSUBUNIT:
		return "SDLK_CURRENCYSUBUNIT";
		case SDLK_KP_LEFTPAREN:
		return "SDLK_KP_LEFTPAREN";
		case SDLK_KP_RIGHTPAREN:
		return "SDLK_KP_RIGHTPAREN";
		case SDLK_KP_LEFTBRACE:
		return "SDLK_KP_LEFTBRACE";
		case SDLK_KP_RIGHTBRACE:
		return "SDLK_KP_RIGHTBRACE";
		case SDLK_KP_TAB:
		return "SDLK_KP_TAB";
		case SDLK_KP_BACKSPACE:
		return "SDLK_KP_BACKSPACE";
		case SDLK_KP_A:
		return "SDLK_KP_A";
		case SDLK_KP_B:
		return "SDLK_KP_B";
		case SDLK_KP_C:
		return "SDLK_KP_C";
		case SDLK_KP_D:
		return "SDLK_KP_D";
		case SDLK_KP_E:
		return "SDLK_KP_E";
		case SDLK_KP_F:
		return "SDLK_KP_F";
		case SDLK_KP_XOR:
		return "SDLK_KP_XOR";
		case SDLK_KP_POWER:
		return "SDLK_KP_POWER";
		case SDLK_KP_PERCENT:
		return "SDLK_KP_PERCENT";
		case SDLK_KP_LESS:
		return "SDLK_KP_LESS";
		case SDLK_KP_GREATER:
		return "SDLK_KP_GREATER";
		case SDLK_KP_AMPERSAND:
		return "SDLK_KP_AMPERSAND";
		case SDLK_KP_DBLAMPERSAND:
		return "SDLK_KP_DBLAMPERSAND";
		case SDLK_KP_VERTICALBAR:
		return "SDLK_KP_VERTICALBAR";
		case SDLK_KP_DBLVERTICALBAR:
		return "SDLK_KP_DBLVERTICALBAR";
		case SDLK_KP_COLON:
		return "SDLK_KP_COLON";
		case SDLK_KP_HASH:
		return "SDLK_KP_HASH";
		case SDLK_KP_SPACE:
		return "SDLK_KP_SPACE";
		case SDLK_KP_AT:
		return "SDLK_KP_AT";
		case SDLK_KP_EXCLAM:
		return "SDLK_KP_EXCLAM";
		case SDLK_KP_MEMSTORE:
		return "SDLK_KP_MEMSTORE";
		case SDLK_KP_MEMRECALL:
		return "SDLK_KP_MEMRECALL";
		case SDLK_KP_MEMCLEAR:
		return "SDLK_KP_MEMCLEAR";
		case SDLK_KP_MEMADD:
		return "SDLK_KP_MEMADD";
		case SDLK_KP_MEMSUBTRACT:
		return "SDLK_KP_MEMSUBTRACT";
		case SDLK_KP_MEMMULTIPLY:
		return "SDLK_KP_MEMMULTIPLY";
		case SDLK_KP_MEMDIVIDE:
		return "SDLK_KP_MEMDIVIDE";
		case SDLK_KP_PLUSMINUS:
		return "SDLK_KP_PLUSMINUS";
		case SDLK_KP_CLEAR:
		return "SDLK_KP_CLEAR";
		case SDLK_KP_CLEARENTRY:
		return "SDLK_KP_CLEARENTRY";
		case SDLK_KP_BINARY:
		return "SDLK_KP_BINARY";
		case SDLK_KP_OCTAL:
		return "SDLK_KP_OCTAL";
		case SDLK_KP_DECIMAL:
		return "SDLK_KP_DECIMAL";
		case SDLK_KP_HEXADECIMAL:
		return "SDLK_KP_HEXADECIMAL";
		case SDLK_LCTRL:
		return "SDLK_LCTRL";
		case SDLK_LSHIFT:
		return "SDLK_LSHIFT";
		case SDLK_LALT:
		return "SDLK_LALT";
		case SDLK_LGUI:
		return "SDLK_LGUI";
		case SDLK_RCTRL:
		return "SDLK_RCTRL";
		case SDLK_RSHIFT:
		return "SDLK_RSHIFT";
		case SDLK_RALT:
		return "SDLK_RALT";
		case SDLK_RGUI:
		return "SDLK_RGUI";
		case SDLK_MODE:
		return "SDLK_MODE";
		case SDLK_AUDIONEXT:
		return "SDLK_AUDIONEXT";
		case SDLK_AUDIOPREV:
		return "SDLK_AUDIOPREV";
		case SDLK_AUDIOSTOP:
		return "SDLK_AUDIOSTOP";
		case SDLK_AUDIOPLAY:
		return "SDLK_AUDIOPLAY";
		case SDLK_AUDIOMUTE:
		return "SDLK_AUDIOMUTE";
		case SDLK_MEDIASELECT:
		return "SDLK_MEDIASELECT";
		case SDLK_WWW:
		return "SDLK_WWW";
		case SDLK_MAIL:
		return "SDLK_MAIL";
		case SDLK_CALCULATOR:
		return "SDLK_CALCULATOR";
		case SDLK_COMPUTER:
		return "SDLK_COMPUTER";
		case SDLK_AC_SEARCH:
		return "SDLK_AC_SEARCH";
		case SDLK_AC_HOME:
		return "SDLK_AC_HOME";
		case SDLK_AC_BACK:
		return "SDLK_AC_BACK";
		case SDLK_AC_FORWARD:
		return "SDLK_AC_FORWARD";
		case SDLK_AC_STOP:
		return "SDLK_AC_STOP";
		case SDLK_AC_REFRESH:
		return "SDLK_AC_REFRESH";
		case SDLK_AC_BOOKMARKS:
		return "SDLK_AC_BOOKMARKS";
		case SDLK_BRIGHTNESSDOWN:
		return "SDLK_BRIGHTNESSDOWN";
		case SDLK_BRIGHTNESSUP:
		return "SDLK_BRIGHTNESSUP";
		case SDLK_DISPLAYSWITCH:
		return "SDLK_DISPLAYSWITCH";
		case SDLK_KBDILLUMTOGGLE:
		return "SDLK_KBDILLUMTOGGLE";
		case SDLK_KBDILLUMDOWN:
		return "SDLK_KBDILLUMDOWN";
		case SDLK_KBDILLUMUP:
		return "SDLK_KBDILLUMUP";
		case SDLK_EJECT:
		return "SDLK_EJECT";
		case SDLK_SLEEP:
		return "SDLK_SLEEP";
	}
	return NULL;
}


void hello_world_run (HelloWorld* self) {
	gboolean quit = FALSE;
	SDL_Event e = {0};
	SDL_Surface* currentSurface = NULL;
	SDL_Surface** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	SDL_Surface* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	quit = FALSE;
	_tmp0_ = self->priv->surfaces;
	_tmp0__length1 = self->priv->surfaces_length1;
	_tmp1_ = _tmp0_[0];
	currentSurface = _tmp1_;
	while (TRUE) {
		gboolean _tmp2_ = FALSE;
		SDL_Surface* _tmp29_ = NULL;
		SDL_Surface* _tmp30_ = NULL;
		SDL_Window* _tmp31_ = NULL;
		_tmp2_ = quit;
		if (!(!_tmp2_)) {
			break;
		}
		while (TRUE) {
			SDL_Event _tmp3_ = {0};
			gint _tmp4_ = 0;
			SDL_Event _tmp5_ = {0};
			SDL_EventType _tmp6_ = 0;
			_tmp4_ = SDL_PollEvent (&_tmp3_);
			 (e);
			e = _tmp3_;
			if (!(_tmp4_ != 0)) {
				break;
			}
			_tmp5_ = e;
			_tmp6_ = _tmp5_.type;
			if (_tmp6_ == SDL_QUIT) {
				quit = TRUE;
			} else {
				SDL_Event _tmp7_ = {0};
				SDL_EventType _tmp8_ = 0;
				_tmp7_ = e;
				_tmp8_ = _tmp7_.type;
				if (_tmp8_ == SDL_KEYDOWN) {
					FILE* _tmp9_ = NULL;
					SDL_Event _tmp10_ = {0};
					SDL_KeyboardEvent _tmp11_ = {0};
					SDL_Keysym _tmp12_ = {0};
					SDL_Keycode _tmp13_ = 0;
					const gchar* _tmp14_ = NULL;
					SDL_Event _tmp15_ = {0};
					SDL_KeyboardEvent _tmp16_ = {0};
					SDL_Keysym _tmp17_ = {0};
					SDL_Keycode _tmp18_ = 0;
					_tmp9_ = stdout;
					_tmp10_ = e;
					_tmp11_ = _tmp10_.key;
					_tmp12_ = _tmp11_.keysym;
					_tmp13_ = _tmp12_.sym;
					_tmp14_ = _sdl_keycode_to_string (_tmp13_);
					fprintf (_tmp9_, "%s\n", _tmp14_);
					_tmp15_ = e;
					_tmp16_ = _tmp15_.key;
					_tmp17_ = _tmp16_.keysym;
					_tmp18_ = _tmp17_.sym;
					switch (_tmp18_) {
						case SDLK_UP:
						{
							SDL_Surface** _tmp19_ = NULL;
							gint _tmp19__length1 = 0;
							SDL_Surface* _tmp20_ = NULL;
							_tmp19_ = self->priv->surfaces;
							_tmp19__length1 = self->priv->surfaces_length1;
							_tmp20_ = _tmp19_[1];
							currentSurface = _tmp20_;
							break;
						}
						case SDLK_DOWN:
						{
							SDL_Surface** _tmp21_ = NULL;
							gint _tmp21__length1 = 0;
							SDL_Surface* _tmp22_ = NULL;
							_tmp21_ = self->priv->surfaces;
							_tmp21__length1 = self->priv->surfaces_length1;
							_tmp22_ = _tmp21_[2];
							currentSurface = _tmp22_;
							break;
						}
						case SDLK_LEFT:
						{
							SDL_Surface** _tmp23_ = NULL;
							gint _tmp23__length1 = 0;
							SDL_Surface* _tmp24_ = NULL;
							_tmp23_ = self->priv->surfaces;
							_tmp23__length1 = self->priv->surfaces_length1;
							_tmp24_ = _tmp23_[3];
							currentSurface = _tmp24_;
							break;
						}
						case SDLK_RIGHT:
						{
							SDL_Surface** _tmp25_ = NULL;
							gint _tmp25__length1 = 0;
							SDL_Surface* _tmp26_ = NULL;
							_tmp25_ = self->priv->surfaces;
							_tmp25__length1 = self->priv->surfaces_length1;
							_tmp26_ = _tmp25_[4];
							currentSurface = _tmp26_;
							break;
						}
						default:
						{
							SDL_Surface** _tmp27_ = NULL;
							gint _tmp27__length1 = 0;
							SDL_Surface* _tmp28_ = NULL;
							_tmp27_ = self->priv->surfaces;
							_tmp27__length1 = self->priv->surfaces_length1;
							_tmp28_ = _tmp27_[0];
							currentSurface = _tmp28_;
							break;
						}
					}
				}
			}
		}
		_tmp29_ = currentSurface;
		_tmp30_ = self->priv->surface;
		SDL_BlitSurface (_tmp29_, NULL, _tmp30_, NULL);
		_tmp31_ = self->priv->window;
		SDL_UpdateWindowSurface (_tmp31_);
	}
	 (e);
}


void hello_world_load_media (HelloWorld* self) {
	SDL_Surface** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	SDL_Surface* _tmp1_ = NULL;
	SDL_Surface* _tmp2_ = NULL;
	SDL_Surface** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	SDL_Surface* _tmp4_ = NULL;
	SDL_Surface* _tmp5_ = NULL;
	SDL_Surface** _tmp6_ = NULL;
	gint _tmp6__length1 = 0;
	SDL_Surface* _tmp7_ = NULL;
	SDL_Surface* _tmp8_ = NULL;
	SDL_Surface** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	SDL_Surface* _tmp10_ = NULL;
	SDL_Surface* _tmp11_ = NULL;
	SDL_Surface** _tmp12_ = NULL;
	gint _tmp12__length1 = 0;
	SDL_Surface* _tmp13_ = NULL;
	SDL_Surface* _tmp14_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->surfaces;
	_tmp0__length1 = self->priv->surfaces_length1;
	_tmp1_ = SDL_LoadBMP ("resources/press.bmp");
	_SDL_FreeSurface0 (_tmp0_[0]);
	_tmp0_[0] = _tmp1_;
	_tmp2_ = _tmp0_[0];
	_tmp3_ = self->priv->surfaces;
	_tmp3__length1 = self->priv->surfaces_length1;
	_tmp4_ = SDL_LoadBMP ("resources/up.bmp");
	_SDL_FreeSurface0 (_tmp3_[1]);
	_tmp3_[1] = _tmp4_;
	_tmp5_ = _tmp3_[1];
	_tmp6_ = self->priv->surfaces;
	_tmp6__length1 = self->priv->surfaces_length1;
	_tmp7_ = SDL_LoadBMP ("resources/down.bmp");
	_SDL_FreeSurface0 (_tmp6_[2]);
	_tmp6_[2] = _tmp7_;
	_tmp8_ = _tmp6_[2];
	_tmp9_ = self->priv->surfaces;
	_tmp9__length1 = self->priv->surfaces_length1;
	_tmp10_ = SDL_LoadBMP ("resources/left.bmp");
	_SDL_FreeSurface0 (_tmp9_[3]);
	_tmp9_[3] = _tmp10_;
	_tmp11_ = _tmp9_[3];
	_tmp12_ = self->priv->surfaces;
	_tmp12__length1 = self->priv->surfaces_length1;
	_tmp13_ = SDL_LoadBMP ("resources/right.bmp");
	_SDL_FreeSurface0 (_tmp12_[4]);
	_tmp12_[4] = _tmp13_;
	_tmp14_ = _tmp12_[4];
}


void hello_world_init (HelloWorld* self) {
	SDL_Window* _tmp0_ = NULL;
	SDL_Window* _tmp1_ = NULL;
	SDL_Surface* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	SDL_Init ((guint32) SDL_INIT_VIDEO);
	_tmp0_ = SDL_CreateWindow ("SDL Tutorial", (gint) SDL_WINDOWPOS_CENTERED_MASK, (gint) SDL_WINDOWPOS_CENTERED_MASK, 640, 480, (guint32) SDL_WINDOW_SHOWN);
	_SDL_DestroyWindow0 (self->priv->window);
	self->priv->window = _tmp0_;
	_tmp1_ = self->priv->window;
	_tmp2_ = SDL_GetWindowSurface (_tmp1_);
	self->priv->surface = _tmp2_;
	hello_world_load_media (self);
}


void hello_world_main (void) {
	HelloWorld* app = NULL;
	HelloWorld* _tmp0_ = NULL;
	_tmp0_ = hello_world_new ();
	app = _tmp0_;
	hello_world_init (app);
	hello_world_run (app);
	_hello_world_unref0 (app);
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	hello_world_main ();
	return 0;
}


HelloWorld* hello_world_construct (GType object_type) {
	HelloWorld* self = NULL;
	self = (HelloWorld*) g_type_create_instance (object_type);
	return self;
}


HelloWorld* hello_world_new (void) {
	return hello_world_construct (TYPE_HELLO_WORLD);
}


static void value_hello_world_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_hello_world_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		hello_world_unref (value->data[0].v_pointer);
	}
}


static void value_hello_world_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = hello_world_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_hello_world_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_hello_world_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		HelloWorld* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = hello_world_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_hello_world_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	HelloWorld** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = hello_world_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_hello_world (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecHelloWorld* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_HELLO_WORLD), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_hello_world (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_HELLO_WORLD), NULL);
	return value->data[0].v_pointer;
}


void value_set_hello_world (GValue* value, gpointer v_object) {
	HelloWorld* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_HELLO_WORLD));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_HELLO_WORLD));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		hello_world_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		hello_world_unref (old);
	}
}


void value_take_hello_world (GValue* value, gpointer v_object) {
	HelloWorld* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_HELLO_WORLD));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_HELLO_WORLD));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		hello_world_unref (old);
	}
}


static void hello_world_class_init (HelloWorldClass * klass) {
	hello_world_parent_class = g_type_class_peek_parent (klass);
	((HelloWorldClass *) klass)->finalize = hello_world_finalize;
	g_type_class_add_private (klass, sizeof (HelloWorldPrivate));
}


static void hello_world_instance_init (HelloWorld * self) {
	SDL_Surface** _tmp0_ = NULL;
	self->priv = HELLO_WORLD_GET_PRIVATE (self);
	_tmp0_ = g_new0 (SDL_Surface*, 5 + 1);
	self->priv->surfaces = _tmp0_;
	self->priv->surfaces_length1 = 5;
	self->priv->_surfaces_size_ = self->priv->surfaces_length1;
	self->ref_count = 1;
}


static void hello_world_finalize (HelloWorld* obj) {
	HelloWorld * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_HELLO_WORLD, HelloWorld);
	g_signal_handlers_destroy (self);
	SDL_Quit ();
	_SDL_DestroyWindow0 (self->priv->window);
	self->priv->surfaces = (_vala_array_free (self->priv->surfaces, self->priv->surfaces_length1, (GDestroyNotify) SDL_FreeSurface), NULL);
}


GType hello_world_get_type (void) {
	static volatile gsize hello_world_type_id__volatile = 0;
	if (g_once_init_enter (&hello_world_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_hello_world_init, value_hello_world_free_value, value_hello_world_copy_value, value_hello_world_peek_pointer, "p", value_hello_world_collect_value, "p", value_hello_world_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (HelloWorldClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) hello_world_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HelloWorld), 0, (GInstanceInitFunc) hello_world_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType hello_world_type_id;
		hello_world_type_id = g_type_register_fundamental (g_type_fundamental_next (), "HelloWorld", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&hello_world_type_id__volatile, hello_world_type_id);
	}
	return hello_world_type_id__volatile;
}


gpointer hello_world_ref (gpointer instance) {
	HelloWorld* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void hello_world_unref (gpointer instance) {
	HelloWorld* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		HELLO_WORLD_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



