# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "06_extension_libraries_and_loading_other_image_formats")
set(06_extension_libraries_and_loading_other_image_formats_VERSION "0.0.0")
set(required_pkgs
  "SDL2_gfx {nocheck,nolink}"
  "SDL2_image"
  "SDL2_ttf"
  "glib-2.0"
  "gobject-2.0"
  "sdl2"
)
set(srcfiles
  "src/test.vala"
)
set(vapifiles
)
set(uifiles
)
