# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "17_mouse_events")
set(17_mouse_events_VERSION "0.0.0")
set(required_pkgs
  "SDL2_gfx {nocheck,nolink}"
  "SDL2_image"
  "SDL2_ttf"
  "glib-2.0"
  "gobject-2.0"
  "sdl2"
)
set(srcfiles
  "src/MyButton.vala"
  "src/MyTexture.vala"
  "src/test.vala"
)
set(vapifiles
)
set(uifiles
)
