# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "02_getting_an_image_on_the_screen")
set(02_getting_an_image_on_the_screen_VERSION "0.0.0")
set(required_pkgs
  "SDL2_gfx {nocheck,nolink}"
  "SDL2_image"
  "SDL2_ttf"
  "glib-2.0"
  "gobject-2.0"
  "sdl2"
)
set(srcfiles
  "src/test.vala"
)
set(vapifiles
)
set(uifiles
)
